version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: flipmemo-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - flipmemo-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: flipmemo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - flipmemo-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: flipmemo-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - flipmemo-network

  flipmemo:
    image: ${DOCKER_REGISTRY-}flipmemo
    build:
      context: .
      dockerfile: FlipMemo/Dockerfile
    container_name: flipmemo-api
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
      - mailhog
    networks:
      - flipmemo-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  flipmemo-network:
    driver: bridge
