version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: flipmemo-postgres
    environment:
      POSTGRES_DB: FlipMemo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flipmemo-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: flipmemo-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@flipmemo.app
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - flipmemo-network

  mailhog:
    image: mailhog/mailhog:latest
    container_name: flipmemo-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    volumes:
      - mailhog_data:/mailhog_data
    environment:
      - MH_STORAGE=maildir
      - MH_MAILDIR_PATH=/mailhog_data
    networks:
      - flipmemo-network

  flipmemo:
    image: ${DOCKER_REGISTRY-}flipmemo
    build:
      context: .
      dockerfile: FlipMemo/Dockerfile
    container_name: flipmemo-api
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - postgres
      - mailhog
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=FlipMemo;Username=postgres;Password=admin
      - Email__Host=mailhog
      - Email__Port=1025
      - Email__Username=
      - Email__Password=
      - Email__From=no-reply@flipmemo.app
    networks:
      - flipmemo-network

volumes:
  postgres_data:
  pgadmin_data:
  mailhog_data:

networks:
  flipmemo-network:
    driver: bridge